// data/products.js
// Data produk dummy untuk ShopList App — 15 produk

export const PRODUCTS = [
  {
    id: '1',
    name: 'Sepatu Lari Nike Air Max',
    category: 'Sepatu',
    price: 1250000,
    rating: 4.8,
    sold: 2341,
    image: '👟',
  },
  {
    id: '2',
    name: 'Kaos Polos Oversize Premium',
    category: 'Pakaian',
    price: 185000,
    rating: 4.5,
    sold: 8920,
    image: '👕',
  },
  {
    id: '3',
    name: 'Celana Jogger Slim Fit',
    category: 'Pakaian',
    price: 235000,
    rating: 4.6,
    sold: 3210,
    image: '👖',
  },
  {
    id: '4',
    name: 'Topi Bucket Vintage',
    category: 'Aksesoris',
    price: 95000,
    rating: 4.3,
    sold: 1567,
    image: '🧢',
  },
  {
    id: '5',
    name: 'Tas Ransel Laptop 15"',
    category: 'Tas',
    price: 345000,
    rating: 4.7,
    sold: 4503,
    image: '🎒',
  },
  {
    id: '6',
    name: 'Hoodie Fleece Tebal',
    category: 'Pakaian',
    price: 275000,
    rating: 4.9,
    sold: 12843,
    image: '🧥',
  },
  {
    id: '7',
    name: 'Sandal Casual Pria',
    category: 'Sepatu',
    price: 120000,
    rating: 4.2,
    sold: 7231,
    image: '🩴',
  },
  {
    id: '8',
    name: 'Jam Tangan Digital Sport',
    category: 'Aksesoris',
    price: 450000,
    rating: 4.6,
    sold: 983,
    image: '⌚',
  },
  {
    id: '9',
    name: 'Kacamata Hitam UV Protection',
    category: 'Aksesoris',
    price: 175000,
    rating: 4.4,
    sold: 2109,
    image: '🕶️',
  },
  {
    id: '10',
    name: 'Jaket Bomber Kulit Sintetis',
    category: 'Pakaian',
    price: 520000,
    rating: 4.8,
    sold: 1876,
    image: '🧣',
  },
  {
    id: '11',
    name: 'Sepatu Sneakers Putih Klasik',
    category: 'Sepatu',
    price: 380000,
    rating: 4.7,
    sold: 5120,
    image: '👞',
  },
  {
    id: '12',
    name: 'Tas Selempang Mini Canvas',
    category: 'Tas',
    price: 150000,
    rating: 4.3,
    sold: 3870,
    image: '👜',
  },
  {
    id: '13',
    name: 'Kemeja Flannel Kotak-kotak',
    category: 'Pakaian',
    price: 210000,
    rating: 4.5,
    sold: 6410,
    image: '👔',
  },
  {
    id: '14',
    name: 'Gelang Kulit Minimalis',
    category: 'Aksesoris',
    price: 65000,
    rating: 4.1,
    sold: 900,
    image: '📿',
  },
  {
    id: '15',
    name: 'Tote Bag Kanvas Polos',
    category: 'Tas',
    price: 85000,
    rating: 4.4,
    sold: 2200,
    image: '🛍️',
  },
];

// Daftar kategori unik (untuk filter chip)
export const CATEGORIES = ['Semua', ...new Set(PRODUCTS.map(p => p.category))];